import pygame

#? --------------------- SCREEN CONSTANTS ----------------
SCREEN_HEIGHT = 700
SCREEN_WIDTH = 800
INITIAL_SHUTTLE_POSITION = [SCREEN_WIDTH/2, SCREEN_HEIGHT-30]
INITIAL_ALIEN_POSITION = [SCREEN_WIDTH/2, 10]
FPS = 400.0
