import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")

SCREEN_HEIGHT = 700
SCREEN_WIDTH = 800
FPS = 60

PLAYER_SPEED = 320
BULLET_SPEED = 520
ALIEN_HORIZONTAL_SPEED = 45
ALIEN_VERTICAL_SPEED = 16
ALIEN_EDGE_PADDING = 20
COLLISION_COOLDOWN_MS = 750

SHUTTLE_HP = 100
SHUTTLE_DAMAGE = 10

INITIAL_SHUTTLE_POSITION = [SCREEN_WIDTH / 2, SCREEN_HEIGHT - 100]
INITIAL_BOSS_POSITION = [SCREEN_WIDTH / 2, SCREEN_HEIGHT - 600]


def asset_path(filename):
    return os.path.join(DATA_DIR, filename)
